#!/bin/bash

set -e

required_packages=(curl git)

for pkg in "${required_packages[@]}"; do
    if dpkg -s "$pkg" &> /dev/null; then
        echo "[✔] $pkg is already installed"
    else
        echo "[ ] $pkg not found. Installing..."
        sudo apt update
        sudo apt install -y "$pkg"
    fi
done



# === Install Argus ===
echo "[*] Installing Argus..."
mkdir -p "\$HOME/.config/argus"

ARGUS_TEMP_DIR=\$(mktemp -d -p "\$HOME")
trap 'rm -rf "\$ARGUS_TEMP_DIR"' EXIT

git clone https://github.com/KillAllChickens/argus "\$ARGUS_TEMP_DIR"
cd "\$ARGUS_TEMP_DIR"
./scripts/install-linux.sh

echo "[✔] Argus successfully completed!."

#? Add more stuff here
