#!/bin/bash

set -e

sudo -v

required_packages=(curl git wget zsh unzip)

for pkg in "${required_packages[@]}"; do
    if dpkg -s "$pkg" &> /dev/null; then
        # echo "[✔] $pkg is already installed"
        ;
    else
        echo "[ ] $pkg not found. Installing..."
        sudo apt update
        sudo apt install -y "$pkg"
    fi
done

sudo apt update

wget https://dl.google.com/dl/earth/client/current/google-earth-pro-stable_current_amd64.deb

sudo apt install ./google-earth-pro-stable_current_amd64.deb

rm google-earth-pro-stable_current_amd64.deb

echo -e "\n\n[✔] Urbex tools have been successfully installed!"
echo "This includes:"
echo -e "\t- Google Earth Pro"